In [ ]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime

path='img'
images=[]
classNames=[]
mylist= os.listdir(path)
print(mylist)

for cl in mylist:
    curimg= cv2.imread(f'{path}/{cl}')
    images.append(curimg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

def findEncodings(images):
    encodeList=[]
    for img in images:
        img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList

def markAttendence(name):
    with open('Attendence.csv','r+') as f:
        myDataList = f.readlines()
        nameList = []
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
            
        if name not in nameList:
            now=datetime.now()
            dtString = now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{dtString}')
            



encodeListKnown = findEncodings(images)
print(len(encodeListKnown))
print("Encoding complete")

cap = cv2.VideoCapture(0)

while True:
    success,img=cap.read()
    imgS = cv2.resize(img,(0,0),None,0.25,0.25)
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)
    
    facesCurFrame = face_recognition.face_locations(imgS)
    encodeCurFrame = face_recognition.face_encodings(imgS,facesCurFrame)
    
    for encodeFace,faceLoc in zip(encodeCurFrame, facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown,encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown,encodeFace)
        print(faceDis)
        
        matchIndex = np.argmin(faceDis)
        
        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)
            y1,x2,y2,x1 = faceLoc
            y1,x2,y2,x1 = y1*4,x2*4,y2*4,x1*4
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            markAttendence(name)
            
    cv2.imshow('Webcam',img)
    cv2.waitKey(1) 

# imgElon = face_recognition.load_image_file("elon_musk.png")
# imgElon = cv2.cvtColor(imgElon,cv2.COLOR_BGR2RGB)

# imgTest = face_recognition.load_image_file("elon_musk2.png")
# imgTest = cv2.cvtColor(imgTest,cv2.COLOR_BGR2RGB)



['Bill.jpg', 'Elonmusk.png', 'Jackma.png']
['Bill', 'Elonmusk', 'Jackma']
3
Encoding complete
[0.849949   0.76574273 0.7521023 ]
[0.87142906 0.83125116 0.78333848]
[0.85681393 0.79867946 0.77897227]
[0.89499545 0.81549355 0.76685093]
[0.88426329 0.81934106 0.74898191]
[0.79746861 0.75885502 0.72860481]
[0.83687787 0.8041023  0.78157037]
[0.83515806 0.80948343 0.76677292]
[0.8195662  0.79400671 0.73937788]
[0.85018787 0.79856303 0.73710303]
[0.83885508 0.80772232 0.74643138]
[0.75218287 0.71763422 0.72050001]
[0.88789878 0.86362471 0.82083341]
[0.88883159 0.81452837 0.74757225]
[0.85936381 0.82119182 0.76064919]
[0.88360013 0.80294769 0.75939574]
[0.85665506 0.71322209 0.43750077]
JACKMA
[0.82710258 0.70497668 0.44918779]
JACKMA
[0.81284617 0.68458532 0.40792548]
JACKMA
[0.85376148 0.726823   0.36024648]
JACKMA
[0.86501126 0.7149112  0.37796764]
JACKMA
[0.8565976  0.71688652 0.3534974 ]
JACKMA
[0.9021236  0.72443775 0.39212138]
JACKMA
[0.86905778 0.71116712 0.39217192]
JACKMA
[0.8931295

In [ ]:
hello